<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class SWCS_Admin {
 public static function init(){ add_action('admin_menu',array(__CLASS__,'menu')); add_action('admin_post_swcs_save_settings',array(__CLASS__,'save_settings')); add_action('admin_post_swcs_download',array(__CLASS__,'download')); add_action('admin_post_swcs_analyse',array(__CLASS__,'analyse')); }
 public static function activate(){ if(false===get_option('swcs_access_key',false)) add_option('swcs_access_key',''); }
 public static function menu(){ add_menu_page('Stricker Catalog Sync','Stricker Sync','manage_options','swcs',array(__CLASS__,'page'),'dashicons-update',56); }
 public static function save_settings(){ if(!current_user_can('manage_options')||!check_admin_referer('swcs_save_settings')) wp_die('Acesso negado.'); update_option('swcs_access_key',sanitize_text_field(wp_unslash($_POST['access_key']??''))); wp_safe_redirect(admin_url('admin.php?page=swcs&saved=1')); exit; }
 public static function download(){ if(!current_user_can('manage_options')||!check_admin_referer('swcs_download')) wp_die('Acesso negado.'); $dataset=sanitize_key(wp_unslash($_POST['dataset']??'')); $result=SWCS_API::download_csv($dataset,'PT'); $args=array('page'=>'swcs','dataset'=>$dataset); if(is_wp_error($result)) $args['error']=rawurlencode($result->get_error_message()); else $args['success']=1; wp_safe_redirect(add_query_arg($args,admin_url('admin.php'))); exit; }
 public static function analyse(){ if(!current_user_can('manage_options')||!check_admin_referer('swcs_analyse')) wp_die('Acesso negado.'); $dataset=sanitize_key(wp_unslash($_POST['dataset']??'')); $result=SWCS_CSV::analyse($dataset); $args=array('page'=>'swcs','dataset'=>$dataset); if(is_wp_error($result)) $args['analysis_error']=rawurlencode($result->get_error_message()); else $args['analysed']=1; wp_safe_redirect(add_query_arg($args,admin_url('admin.php'))); exit; }
 private static function option_summary($r){ $parts=array(); if(!empty($r['has_colors'])) $parts[]='Cores'.(!empty($r['colors'])?' ('.count($r['colors']).')':''); if(!empty($r['has_sizes'])) $parts[]='Tamanhos'.(!empty($r['sizes'])?' ('.count($r['sizes']).')':''); if(!empty($r['has_capacity'])) $parts[]='Capacidades'.(!empty($r['capacity'])?' ('.count($r['capacity']).')':''); return $parts ? implode(', ',$parts) : 'Nenhuma'; }
 public static function page(){
  $datasets=array('producttypes'=>'Product Types','products'=>'Products','optionals'=>'Optionals','optionalsPrice'=>'Optionals Price','optionalscomplete'=>'Optionals Complete','customizationOptions'=>'Customization Options','customizationTables'=>'Customization Tables','colors'=>'Colors','stocks'=>'Stocks');
  $diagnostic = null; $diagnostic_error = ''; $diag_page = max(1,(int)($_GET['diag_page']??1)); $diag_per_page = min(100,max(10,(int)($_GET['diag_per_page']??25))); $diag_search = sanitize_text_field(wp_unslash($_GET['diag_search']??''));
  if(isset($_GET['diag'])){ $diagnostic=SWCS_Catalog_Diagnostic::get_products($diag_page,$diag_per_page,$diag_search); if(is_wp_error($diagnostic)){ $diagnostic_error=$diagnostic->get_error_message(); $diagnostic=null; } }
  $detail = null; if(isset($_GET['product_ref']) && '' !== (string)$_GET['product_ref']) { $detail=SWCS_Catalog_Diagnostic::get_product(sanitize_text_field(wp_unslash($_GET['product_ref']))); }
  ?>
  <div class="wrap"><h1>Stricker WooCommerce Catalog Sync CSV</h1>
  <?php if(isset($_GET['saved'])):?><div class="notice notice-success"><p>Access key salva com sucesso.</p></div><?php endif;?>
  <?php if(isset($_GET['success'])):?><div class="notice notice-success"><p>Download de <?php echo esc_html($_GET['dataset']??'');?> concluído com sucesso.</p></div><?php endif;?>
  <?php if(isset($_GET['analysed'])):?><div class="notice notice-success"><p>Análise do CSV concluída.</p></div><?php endif;?>
  <?php if(isset($_GET['error'])):?><div class="notice notice-error"><p><?php echo esc_html(wp_unslash($_GET['error']));?></p></div><?php endif;?>
  <?php if(isset($_GET['analysis_error'])):?><div class="notice notice-error"><p><?php echo esc_html(wp_unslash($_GET['analysis_error']));?></p></div><?php endif;?>
  <h2>Conexão</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="swcs_save_settings"><?php wp_nonce_field('swcs_save_settings');?><table class="form-table"><tr><th><label for="swcs-access-key">Access Key</label></th><td><input id="swcs-access-key" name="access_key" type="password" class="regular-text" value="<?php echo esc_attr(SWCS_API::get_access_key());?>" autocomplete="off"></td></tr></table><?php submit_button('Salvar Access Key');?></form>
  <h2>Catálogos CSV</h2><p>Os arquivos são baixados localmente para posterior processamento. Esta etapa não cria nem altera produtos do WooCommerce.</p><table class="widefat striped"><thead><tr><th>Dataset</th><th>Status</th><th>Ações</th></tr></thead><tbody>
  <?php foreach($datasets as $key=>$label): $status=get_option('swcs_catalog_'.$key.'_status',array()); $analysis=get_option('swcs_catalog_'.$key.'_analysis',array()); ?>
   <tr><td><strong><?php echo esc_html($label);?></strong></td><td><?php echo !empty($status['completed'])?'Concluído em '.esc_html($status['completed']).' ('.esc_html(size_format((int)($status['size']??0))).')':'Ainda não baixado';?></td><td><?php if(!empty($status['completed'])):?><form style="display:inline-block;margin-right:6px" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('swcs_analyse');?><input type="hidden" name="action" value="swcs_analyse"><input type="hidden" name="dataset" value="<?php echo esc_attr($key);?>"><?php submit_button('Analisar CSV','secondary','submit',false);?></form><?php endif;?><form style="display:inline-block" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('swcs_download');?><input type="hidden" name="action" value="swcs_download"><input type="hidden" name="dataset" value="<?php echo esc_attr($key);?>"><?php submit_button('Baixar CSV','secondary','submit',false);?></form></td></tr>
   <?php if(!empty($analysis)):?><tr><td colspan="3"><div style="padding:10px 15px;background:#f6f7f7"><strong>Análise:</strong> <?php echo esc_html(number_format_i18n((int)$analysis['records']));?> registros · <?php echo esc_html((int)$analysis['columns']);?> colunas · delimitador <code><?php echo esc_html($analysis['delimiter']==="\t"?'TAB':$analysis['delimiter']);?></code> · <?php echo esc_html($analysis['encoding']);?> · analisado em <?php echo esc_html($analysis['analysed']);?><br><strong>Colunas:</strong> <?php echo esc_html(implode(', ',$analysis['header']));?><details style="margin-top:8px"><summary>Ver amostra dos primeiros 10 registros</summary><pre style="max-height:350px;overflow:auto;background:#fff;padding:10px"><?php echo esc_html(wp_json_encode($analysis['sample'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));?></pre></details></div></td></tr><?php endif;?>
  <?php endforeach;?></tbody></table>
  <hr><h2>Diagnóstico do catálogo</h2><p>Esta tela cruza o <strong>Products</strong> com <strong>Product Types</strong> e interpreta, de forma preliminar, a presença de cores, tamanhos e capacidades. Os valores detalhados das opções serão cruzados com os datasets de <strong>Optionals</strong> e <strong>Optionals Complete</strong> em uma próxima etapa. <strong>Nenhum produto é criado ou alterado no WooCommerce.</strong></p>
  <form method="get" style="margin:12px 0"><input type="hidden" name="page" value="swcs"><input type="hidden" name="diag" value="1"><input type="search" name="diag_search" value="<?php echo esc_attr($diag_search);?>" placeholder="Buscar referência, nome ou categoria" class="regular-text"><select name="diag_per_page"><option value="25" <?php selected($diag_per_page,25);?>>25</option><option value="50" <?php selected($diag_per_page,50);?>>50</option><option value="100" <?php selected($diag_per_page,100);?>>100</option></select> <?php submit_button('Analisar catálogo','primary','submit',false);?></form>
  <?php if($diagnostic_error):?><div class="notice notice-error"><p><?php echo esc_html($diagnostic_error);?></p></div><?php endif;?>
  <?php if(is_array($diagnostic)):?><p><strong><?php echo esc_html(number_format_i18n($diagnostic['total']));?></strong> produtos encontrados. Página <?php echo esc_html($diagnostic['page']);?> de <?php echo esc_html($diagnostic['pages']);?>.</p><table class="widefat striped"><thead><tr><th>Ref.</th><th>Produto</th><th>Categoria</th><th>Subcategoria</th><th>Opções detectadas</th><th>WooCommerce</th><th></th></tr></thead><tbody><?php foreach($diagnostic['rows'] as $r):?><tr><td><?php echo esc_html($r['reference']);?></td><td><?php echo esc_html($r['name']);?></td><td><?php echo esc_html($r['type_code'].' '.$r['type_name']);?></td><td><?php echo esc_html($r['subtype_code'].' '.$r['subtype_name']);?></td><td><?php echo esc_html(self::option_summary($r));?></td><td><?php echo esc_html($r['woocommerce_type']);?></td><td><a class="button button-small" href="<?php echo esc_url(add_query_arg(array('page'=>'swcs','product_ref'=>$r['reference']),admin_url('admin.php')));?>">Detalhes</a></td></tr><?php endforeach;?></tbody></table>
  <div style="margin-top:12px"><?php for($i=max(1,$diagnostic['page']-3);$i<=min($diagnostic['pages'],$diagnostic['page']+3);$i++):?><a class="button <?php echo $i===$diagnostic['page']?'button-primary':'';?>" style="margin-right:4px" href="<?php echo esc_url(add_query_arg(array('page'=>'swcs','diag'=>1,'diag_page'=>$i,'diag_per_page'=>$diag_per_page,'diag_search'=>$diag_search),admin_url('admin.php')));?>"><?php echo esc_html($i);?></a><?php endfor;?></div><?php endif;?>
  <?php if(is_array($detail)):?><hr><h2>Detalhes do produto <?php echo esc_html($detail['reference']);?></h2><p><a href="<?php echo esc_url(add_query_arg(array('page'=>'swcs','diag'=>1,'diag_page'=>$diag_page,'diag_per_page'=>$diag_per_page,'diag_search'=>$diag_search),admin_url('admin.php')));?>">← Voltar ao diagnóstico</a></p><table class="widefat striped" style="max-width:1000px"><tbody><?php foreach(array('name'=>'Nome','description'=>'Descrição','short_description'=>'Descrição curta','type_name'=>'Categoria','subtype_name'=>'Subcategoria','woocommerce_type'=>'Classificação WooCommerce') as $k=>$label):?><tr><th style="width:180px"><?php echo esc_html($label);?></th><td><?php echo esc_html($detail[$k]);?></td></tr><?php endforeach;?><tr><th>Tem cores?</th><td><?php echo $detail['has_colors']?'Sim':'Não';?></td></tr><tr><th>Tem tamanhos?</th><td><?php echo $detail['has_sizes']?'Sim':'Não';?></td></tr><tr><th>Tem capacidades?</th><td><?php echo $detail['has_capacity']?'Sim':'Não';?></td></tr><tr><th>Cores detectadas no Products</th><td><?php echo esc_html($detail['colors']?implode(', ',$detail['colors']):'Nenhuma');?></td></tr><tr><th>Tamanhos detectados no Products</th><td><?php echo esc_html($detail['sizes']?implode(', ',$detail['sizes']):'Nenhum');?></td></tr><tr><th>Capacidades detectadas no Products</th><td><?php echo esc_html($detail['capacity']?implode(', ',$detail['capacity']):'Nenhuma');?></td></tr></tbody></table><details style="margin-top:12px"><summary>Campos brutos usados no diagnóstico</summary><pre style="max-height:500px;overflow:auto;background:#fff;border:1px solid #ccd0d4;padding:12px"><?php echo esc_html(wp_json_encode($detail['raw']??$detail,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));?></pre></details><?php elseif(isset($_GET['product_ref']) && '' !== (string)$_GET['product_ref']):?><div class="notice notice-error"><p><?php echo esc_html(is_wp_error($detail)?$detail->get_error_message():'Produto não encontrado.');?></p></div><?php endif;?>
  </div><?php }
}